spring:
  application:
    name: admin-discovery

#Spring Boot Admin Configuration
boot:
  admin:
    discovery:
      enabled: true
    context-path: /spring-admin/

server:
  port: 8091
  http2:
    enabled: true
  context:
    context-path: /
management:
  server:
    port: 8091
    servlet:
      context-path: /admin

custom-props:
  home-protocol: http
  home-url: localhost
  local-server: ${custom-props.home-protocol}://${custom-props.home-url}:${server.port} #server Location
  admin-discovery-server: http://localhost:8091 #admin discovery server location
  log-file-root: C:\\logs


#Eureka Discovery Configuration
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
      
logging:
  level:
    org.springframework.security: DEBUG
    com.uniteller: DEBUG
  file:
    name: ${custom-props.log-file-root}/business-${spring.application.name}.log
