logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.yourcompany.businessservice: DEBUG
    com.hibernate.SQL: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:

aws:
  s3:
    service:
      base-url: http://localhost:9003
      connection-timeout: 30000
      read-timeout: 60000
      upload-endpoint: /aws/s3/upload