spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # Maximum file size
      max-request-size: 50MB   # Maximum request size (for multiple files)

# AWS S3 Configuration
aws:
  s3:
    access-key: AKIAUZR2RGGHVN4BH6IA
    secret-key: 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
    region: ap-south-1
    bucket-name: stayeaze-booking-app

logging:
  level:
    com.amazonaws: DEBUG

# File Upload Configuration
file:
  upload:
    allowed-extensions: jpg,jpeg,png,gif,webp
    max-file-size: 10485760  # 10MB in bytes