server:
  port: 8998
  http2:
    enabled: true
spring:
  application:
    name: config-service
  profiles:
    active: native #Tells Spring Cloud Config Server to load configuration files from the local filesystem or classpath instead of Git, SVN, or other remote repositories


custom-props:
  home-protocol: https
  home-url: stayeaze
  local-server: ${custom-props.home-protocol}://${custom-props.home-url}:${server.port}
  log-file-root: ${LOG_FILE_LOCATION:C:\\logs}

logging:
  file:
    name: ${custom-props.log-file-root}/${spring.application.name}.log