version: '3.8'

services:
  config-server:
    image: config-server:1.0 
    container_name: config-server
    ports:
      - "8998:8998"
    networks:
      - stayeaze-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8998/actuator/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 20s

  booking-service:
    image: booking:1.0
    container_name: booking-service
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - stayeaze-network

networks:
  stayeaze-network:
    driver: bridge