spring:
  application:
    name: api-gateway
  profiles:
    active: redis
  cloud:
    config:
      request-read-timeout: 5000
      fail-fast: true
      name: business, api-gateway
      label: master
  main:
    allow-bean-definition-overriding: true

  config:
    import:
      - configserver:http://localhost:8998