spring:
  application:
    name: notification
  profiles:
    active: notification
  cloud:
    config:
      request-read-timeout: 5000
      fail-fast: true
      name: business
      label: master
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - configserver:http://stayeaze:8998