spring:
  application:
    name: auth-service
  profiles:
    active: auth, db, redis
  cloud:
    config:
      request-read-timeout: 5000
      fail-fast: true
      name: business
      label: master
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - configserver:http://localhost:8998