server:
  port: 9004

spring:
  application:
    name: notification

#--------------------------------------------------------------------
#               E-MAIL Service Configuration
#--------------------------------------------------------------------
spring.mail:
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  username: shivanshrahangdale@gmail.com
  password: yvnm cpxx xdel vzde
  test-connection: false
  default-encoding: UTF-8
  properties:
    mail:
      debug: true
      smtp:
        auth: true
        trust: smtp.gmail.com
        starttls:
          enable: true
#--------------------------------------------------------------------